//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class CalibrateBuoyancyGoal : Message
    {
        public const string k_RosMessageName = "riptide_msgs/CalibrateBuoyancy";
        public override string RosMessageName => k_RosMessageName;

        // goal definition

        public CalibrateBuoyancyGoal()
        {
        }
        public static CalibrateBuoyancyGoal Deserialize(MessageDeserializer deserializer) => new CalibrateBuoyancyGoal(deserializer);

        private CalibrateBuoyancyGoal(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "CalibrateBuoyancyGoal: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
