//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class CalibrateDragResult : Message
    {
        public const string k_RosMessageName = "riptide_msgs/CalibrateDrag";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public double[] linear_drag;
        public double[] quadratic_drag;

        public CalibrateDragResult()
        {
            this.linear_drag = new double[0];
            this.quadratic_drag = new double[0];
        }

        public CalibrateDragResult(double[] linear_drag, double[] quadratic_drag)
        {
            this.linear_drag = linear_drag;
            this.quadratic_drag = quadratic_drag;
        }

        public static CalibrateDragResult Deserialize(MessageDeserializer deserializer) => new CalibrateDragResult(deserializer);

        private CalibrateDragResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.linear_drag, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.quadratic_drag, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.linear_drag);
            serializer.Write(this.linear_drag);
            serializer.WriteLength(this.quadratic_drag);
            serializer.Write(this.quadratic_drag);
        }

        public override string ToString()
        {
            return "CalibrateDragResult: " +
            "\nlinear_drag: " + System.String.Join(", ", linear_drag.ToList()) +
            "\nquadratic_drag: " + System.String.Join(", ", quadratic_drag.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
