//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class CalibrateBuoyancyResult : Message
    {
        public const string k_RosMessageName = "riptide_msgs/CalibrateBuoyancy";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public double buoyant_force;
        public double[] center_of_buoyancy;

        public CalibrateBuoyancyResult()
        {
            this.buoyant_force = 0.0;
            this.center_of_buoyancy = new double[0];
        }

        public CalibrateBuoyancyResult(double buoyant_force, double[] center_of_buoyancy)
        {
            this.buoyant_force = buoyant_force;
            this.center_of_buoyancy = center_of_buoyancy;
        }

        public static CalibrateBuoyancyResult Deserialize(MessageDeserializer deserializer) => new CalibrateBuoyancyResult(deserializer);

        private CalibrateBuoyancyResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.buoyant_force);
            deserializer.Read(out this.center_of_buoyancy, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.buoyant_force);
            serializer.WriteLength(this.center_of_buoyancy);
            serializer.Write(this.center_of_buoyancy);
        }

        public override string ToString()
        {
            return "CalibrateBuoyancyResult: " +
            "\nbuoyant_force: " + buoyant_force.ToString() +
            "\ncenter_of_buoyancy: " + System.String.Join(", ", center_of_buoyancy.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
