//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ExecuteTaskFeedback : Message
    {
        public const string k_RosMessageName = "riptide_msgs/ExecuteTask";
        public override string RosMessageName => k_RosMessageName;

        // feedback
        public string stdout_data;
        public string stderr_data;

        public ExecuteTaskFeedback()
        {
            this.stdout_data = "";
            this.stderr_data = "";
        }

        public ExecuteTaskFeedback(string stdout_data, string stderr_data)
        {
            this.stdout_data = stdout_data;
            this.stderr_data = stderr_data;
        }

        public static ExecuteTaskFeedback Deserialize(MessageDeserializer deserializer) => new ExecuteTaskFeedback(deserializer);

        private ExecuteTaskFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stdout_data);
            deserializer.Read(out this.stderr_data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stdout_data);
            serializer.Write(this.stderr_data);
        }

        public override string ToString()
        {
            return "ExecuteTaskFeedback: " +
            "\nstdout_data: " + stdout_data.ToString() +
            "\nstderr_data: " + stderr_data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
