//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ExecuteTaskGoal : Message
    {
        public const string k_RosMessageName = "riptide_msgs/ExecuteTask";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public string behaviortree_file;

        public ExecuteTaskGoal()
        {
            this.behaviortree_file = "";
        }

        public ExecuteTaskGoal(string behaviortree_file)
        {
            this.behaviortree_file = behaviortree_file;
        }

        public static ExecuteTaskGoal Deserialize(MessageDeserializer deserializer) => new ExecuteTaskGoal(deserializer);

        private ExecuteTaskGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.behaviortree_file);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.behaviortree_file);
        }

        public override string ToString()
        {
            return "ExecuteTaskGoal: " +
            "\nbehaviortree_file: " + behaviortree_file.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
