//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class FollowTrajectoryGoal : Message
    {
        public const string k_RosMessageName = "riptide_msgs/FollowTrajectory";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Trajectory.MultiDOFJointTrajectoryMsg trajectory;

        public FollowTrajectoryGoal()
        {
            this.trajectory = new Trajectory.MultiDOFJointTrajectoryMsg();
        }

        public FollowTrajectoryGoal(Trajectory.MultiDOFJointTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static FollowTrajectoryGoal Deserialize(MessageDeserializer deserializer) => new FollowTrajectoryGoal(deserializer);

        private FollowTrajectoryGoal(MessageDeserializer deserializer)
        {
            this.trajectory = Trajectory.MultiDOFJointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "FollowTrajectoryGoal: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
