//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class FollowTrajectoryFeedback : Message
    {
        public const string k_RosMessageName = "riptide_msgs/FollowTrajectory";
        public override string RosMessageName => k_RosMessageName;

        // feedback
        public float progress;

        public FollowTrajectoryFeedback()
        {
            this.progress = 0.0f;
        }

        public FollowTrajectoryFeedback(float progress)
        {
            this.progress = progress;
        }

        public static FollowTrajectoryFeedback Deserialize(MessageDeserializer deserializer) => new FollowTrajectoryFeedback(deserializer);

        private FollowTrajectoryFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.progress);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.progress);
        }

        public override string ToString()
        {
            return "FollowTrajectoryFeedback: " +
            "\nprogress: " + progress.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
