//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ScriptOhioFeedback : Message
    {
        public const string k_RosMessageName = "riptide_msgs/ScriptOhio";
        public override string RosMessageName => k_RosMessageName;

        // feedback

        public ScriptOhioFeedback()
        {
        }
        public static ScriptOhioFeedback Deserialize(MessageDeserializer deserializer) => new ScriptOhioFeedback(deserializer);

        private ScriptOhioFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ScriptOhioFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
