//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class SickTrickGoal : Message
    {
        public const string k_RosMessageName = "riptide_msgs/SickTrick";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public string trick;

        public SickTrickGoal()
        {
            this.trick = "";
        }

        public SickTrickGoal(string trick)
        {
            this.trick = trick;
        }

        public static SickTrickGoal Deserialize(MessageDeserializer deserializer) => new SickTrickGoal(deserializer);

        private SickTrickGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trick);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trick);
        }

        public override string ToString()
        {
            return "SickTrickGoal: " +
            "\ntrick: " + trick.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
