//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ThrusterTestFeedback : Message
    {
        public const string k_RosMessageName = "riptide_msgs/ThrusterTest";
        public override string RosMessageName => k_RosMessageName;

        // feedback

        public ThrusterTestFeedback()
        {
        }
        public static ThrusterTestFeedback Deserialize(MessageDeserializer deserializer) => new ThrusterTestFeedback(deserializer);

        private ThrusterTestFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ThrusterTestFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
