//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ThrusterTestGoal : Message
    {
        public const string k_RosMessageName = "riptide_msgs/ThrusterTest";
        public override string RosMessageName => k_RosMessageName;

        // goal definition

        public ThrusterTestGoal()
        {
        }
        public static ThrusterTestGoal Deserialize(MessageDeserializer deserializer) => new ThrusterTestGoal(deserializer);

        private ThrusterTestGoal(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ThrusterTestGoal: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
