mass: 10.0
com:
- 0.0
- 0.0
- 0.0
base_link:
- 0.0
- 0.0
- 0.0
thrusters:
- name: VUS
  type: 1
  pose:
  - -0.134
  - -0.369
  - 0.242
  - 0.0
  - 0.0
  - 0.0
- name: VUP
  type: 0
  pose:
  - -0.134
  - 0.438
  - 0.242
  - 0.0
  - 0.0
  - 0.0
- name: HUS
  type: 0
  pose:
  - -0.14
  - -0.26
  - 0.141
  - 0.0
  - -0.785
  - 1.571
- name: HUP
  type: 1
  pose:
  - -0.14
  - 0.328
  - 0.141
  - 0.0
  - -0.785
  - -1.571
cameras:
- name: survey
  pose:
  - 0.25
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
