/**/riptide_mapping2:
  ros__parameters:
    cov_limit: 0.01
    k_value: 0.1
    detection_cov_factor: 7.0
    angle_cutoff: 15.0
    distance_limit: 10.0
    confidence_cutoff: 0.2
    quantile:
    - 0.01
    - 0.99
    minimum_distance: 1.0
    bin_fit:
      residual_tol_m: 0.1
      baseline_tol_m: 0.1
      min_baseline_m: 0.2
      cov_floor_m2: 0.0025
      z_consistency_tol_m: 0.1
/**/zed_faker:
  ros__parameters:
    config_frame: tag
    map_origin_pool:
    - 19.5136
    - 0.0
    - 90.0
/course/riptide_mapping2:
  ros__parameters:
    init_data:
      gate:
        parent: map
        covar:
          x: 20.0
          y: 20.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 4.810167
          y: -2.217889
          z: -0.75
          yaw: 170.645069
      gate_rescue:
        parent: gate_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 0.0
          y: 0.75
          z: 0.5
          yaw: 0.0
      gate_repair:
        parent: gate_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 0.0
          y: -0.75
          z: 0.5
          yaw: 0.0
      pre_return_home:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 16.410646
          y: -4.05827
          z: -1.372
          yaw: 90.226263
      slalom_parent:
        parent: map
        lock_orientation_to_config: true
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 0.001
        pose:
          x: 8.332382
          y: 0.560795
          z: -1.3
          yaw: -152.691724
      slalom_front:
        parent: slalom_parent_frame
        lock_orientation_to_config: true
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: 0.0
          yaw: 0.0
      slalom_middle:
        parent: slalom_front_frame
        lock_orientation_to_config: true
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 0.001
        pose:
          x: -2.127361
          y: 0.693981
          z: 0.0
          yaw: 0.0
      slalom_back:
        parent: slalom_front_frame
        lock_orientation_to_config: true
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 0.001
        pose:
          x: -4.231969
          y: 0.117814
          z: 0.0
          yaw: 0.0
      pre_torpedo_pose:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 16.849613
          y: 2.888054
          z: -1.372
          yaw: -0.029345
      torpedo:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 18.35222
          y: 2.480545
          z: -1.372
          yaw: -169.835651
      fire_hole_large:
        parent: torpedo_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 0.0
          y: -0.029972
          z: 0.217424
          yaw: 0.0
      fire_hole_small:
        parent: torpedo_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.11176
          z: -0.0889
          yaw: 0.0
      blood_hole_large:
        parent: torpedo_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 0.0
          y: -0.029972
          z: 0.217424
          yaw: 0.0
      blood_hole_small:
        parent: torpedo_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.11176
          z: -0.0889
          yaw: 0.0
      pre_bin_pose:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 13.222851
          y: 10.242817
          z: -1.3
          yaw: 0.0
      post_bin_pose:
        parent: pre_bin_pose_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: 0.5
          yaw: 0.0
      bin:
        parent: map
        class: fire
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 13.408019
          y: 12.324713
          z: -2.13
          yaw: -145.070841
      bin_target1:
        parent: bin_frame
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: 0.3
          yaw: 0.0
      bin_target2:
        parent: bin_frame
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: 0.3
          yaw: 0.0
      bin_cad_geometry:
        parent: bin_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: 0.0
          yaw: 0.0
      magnet_target1:
        parent: bin_cad_geometry_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.76512
          y: 0.37018
          z: 0.15975
          yaw: 0.0
      magnet_target2:
        parent: bin_cad_geometry_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.70442
          y: -0.37018
          z: 0.466
          yaw: 180.0
      magnet1:
        parent: bin_cad_geometry_frame
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.76512
          y: 0.37018
          z: 0.15975
          yaw: 0.0
      magnet2:
        parent: bin_cad_geometry_frame
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.70442
          y: -0.37018
          z: 0.466
          yaw: 180.0
      bin_vinyl1:
        parent: bin_cad_geometry_frame
        class: blood
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.474
          y: -0.122
          z: 0.301
          yaw: 0.0
      bin_vinyl2:
        parent: bin_cad_geometry_frame
        class: fire
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.237
          y: 0.347
          z: 0.335
          yaw: 0.0
      bin_vinyl3:
        parent: bin_cad_geometry_frame
        class: fire
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.21663
          y: -0.3466
          z: 0.47036
          yaw: 0.0
      bin_vinyl4:
        parent: bin_cad_geometry_frame
        class: blood
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.43325
          y: 0.12206
          z: 0.57196
          yaw: 0.0
      table:
        parent: map
        lock_orientation_to_config: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 19.290761
          y: 9.007
          z: -1.54
          yaw: 89.039804
      pill:
        parent: table_frame
        point_yaw_at_parent: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.082859
          y: 0.192053
          z: 0.05
          yaw: 180.0
      bandage:
        parent: table_frame
        point_yaw_at_parent: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.068547
          y: -0.133469
          z: 0.03
          yaw: 180.0
      nut_and_bolt:
        parent: table_frame
        point_yaw_at_parent: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.15
          y: 0.15
          z: 0.05
          yaw: 0.0
      plug:
        parent: table_frame
        point_yaw_at_parent: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.25
          y: -0.25
          z: 0.03
          yaw: 0.0
      helmet:
        parent: table_frame
        point_yaw_at_parent: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.40168
          y: 0.0
          z: 0.021457
          yaw: 0.0
      warning:
        parent: table_frame
        point_yaw_at_parent: true
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.40168
          y: 0.0
          z: 0.021457
          yaw: 0.0
      octagon:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.082085
          y: -0.064919
          z: 1.2352
          yaw: -134.313351
      compass:
        parent: octagon_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 0.0
          y: 1.38
          z: 0.0
          yaw: -90.0
      hammer_and_wrench:
        parent: octagon_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 0.0
          y: -1.38
          z: 0.0
          yaw: 90.0
      buoy:
        parent: octagon_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: -1.38
          y: 0.0
          z: 0.0
          yaw: 0.0
      sos:
        parent: octagon_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 1.38
          y: -0.0
          z: 0.0
          yaw: 180.0
      pre_table_pose:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 17.889498
          y: 8.447664
          z: -1.3
          yaw: 0.0
      post_table_pose:
        parent: pre_table_pose_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 0.0
          y: 0.0
          z: 0.5
          yaw: 0.0
      prequal_gate:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 4.0
          y: 0.0
          z: -1.5
          yaw: 180.0
      prequal_pole:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 14.0
          y: 0.0
          z: -1.5
          yaw: 180.0
    buffer_size: 60
