<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>camera_faker</name>
  <version>0.0.0</version>
  <description>OpenGL RoboSub visualization with simulated ZED X Mini forward and downward cameras.</description>
  <maintainer email="beckernm@gmail.com">uwrt</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>std_srvs</depend>
  <depend>riptide_msgs2</depend>
  <exec_depend>c_simulator</exec_depend>
  <exec_depend>riptide_meshes</exec_depend>
  <exec_depend>riptide_descriptions2</exec_depend>
  <exec_depend>apriltag_ros</exec_depend>
  <exec_depend>riptide_hardware2</exec_depend>
  <exec_depend>riptide_rviz</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <depend>libassimp-dev</depend>
  <depend>yaml-cpp</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>glfw</depend>
  <depend>OpenCV</depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
