//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class AcousticsStatusMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/AcousticsStatus";
        public override string RosMessageName => k_RosMessageName;

        public float pfpa_diff;
        public float pfsf_diff;
        public float angle;

        public AcousticsStatusMsg()
        {
            this.pfpa_diff = 0.0f;
            this.pfsf_diff = 0.0f;
            this.angle = 0.0f;
        }

        public AcousticsStatusMsg(float pfpa_diff, float pfsf_diff, float angle)
        {
            this.pfpa_diff = pfpa_diff;
            this.pfsf_diff = pfsf_diff;
            this.angle = angle;
        }

        public static AcousticsStatusMsg Deserialize(MessageDeserializer deserializer) => new AcousticsStatusMsg(deserializer);

        private AcousticsStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pfpa_diff);
            deserializer.Read(out this.pfsf_diff);
            deserializer.Read(out this.angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pfpa_diff);
            serializer.Write(this.pfsf_diff);
            serializer.Write(this.angle);
        }

        public override string ToString()
        {
            return "AcousticsStatusMsg: " +
            "\npfpa_diff: " + pfpa_diff.ToString() +
            "\npfsf_diff: " + pfsf_diff.ToString() +
            "\nangle: " + angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
