//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class AcousticsCommandMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/AcousticsCommand";
        public override string RosMessageName => k_RosMessageName;

        public sbyte enabled;
        public int ping_frequency;
        public string file_name;

        public AcousticsCommandMsg()
        {
            this.enabled = 0;
            this.ping_frequency = 0;
            this.file_name = "";
        }

        public AcousticsCommandMsg(sbyte enabled, int ping_frequency, string file_name)
        {
            this.enabled = enabled;
            this.ping_frequency = ping_frequency;
            this.file_name = file_name;
        }

        public static AcousticsCommandMsg Deserialize(MessageDeserializer deserializer) => new AcousticsCommandMsg(deserializer);

        private AcousticsCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enabled);
            deserializer.Read(out this.ping_frequency);
            deserializer.Read(out this.file_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enabled);
            serializer.Write(this.ping_frequency);
            serializer.Write(this.file_name);
        }

        public override string ToString()
        {
            return "AcousticsCommandMsg: " +
            "\nenabled: " + enabled.ToString() +
            "\nping_frequency: " + ping_frequency.ToString() +
            "\nfile_name: " + file_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
