//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class AlignmentCommandMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/AlignmentCommand";
        public override string RosMessageName => k_RosMessageName;

        public string @object;
        public double width_ratio;

        public AlignmentCommandMsg()
        {
            this.@object = "";
            this.width_ratio = 0.0;
        }

        public AlignmentCommandMsg(string @object, double width_ratio)
        {
            this.@object = @object;
            this.width_ratio = width_ratio;
        }

        public static AlignmentCommandMsg Deserialize(MessageDeserializer deserializer) => new AlignmentCommandMsg(deserializer);

        private AlignmentCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@object);
            deserializer.Read(out this.width_ratio);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@object);
            serializer.Write(this.width_ratio);
        }

        public override string ToString()
        {
            return "AlignmentCommandMsg: " +
            "\n@object: " + @object.ToString() +
            "\nwidth_ratio: " + width_ratio.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
