//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class BoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/BoundingBox";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg top_left;
        public Geometry.PointMsg bottom_right;

        public BoundingBoxMsg()
        {
            this.top_left = new Geometry.PointMsg();
            this.bottom_right = new Geometry.PointMsg();
        }

        public BoundingBoxMsg(Geometry.PointMsg top_left, Geometry.PointMsg bottom_right)
        {
            this.top_left = top_left;
            this.bottom_right = bottom_right;
        }

        public static BoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxMsg(deserializer);

        private BoundingBoxMsg(MessageDeserializer deserializer)
        {
            this.top_left = Geometry.PointMsg.Deserialize(deserializer);
            this.bottom_right = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.top_left);
            serializer.Write(this.bottom_right);
        }

        public override string ToString()
        {
            return "BoundingBoxMsg: " +
            "\ntop_left: " + top_left.ToString() +
            "\nbottom_right: " + bottom_right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
