//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ControllerEnableMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/ControllerEnable";
        public override string RosMessageName => k_RosMessageName;

        public sbyte controller;
        //  which controller to select:
        //  0 = Linear P controllers
        public const sbyte LINEAR = 0; //  1 = AUV_GNC LQR Controller
        public const sbyte LQR = 1;

        public ControllerEnableMsg()
        {
            this.controller = 0;
        }

        public ControllerEnableMsg(sbyte controller)
        {
            this.controller = controller;
        }

        public static ControllerEnableMsg Deserialize(MessageDeserializer deserializer) => new ControllerEnableMsg(deserializer);

        private ControllerEnableMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.controller);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.controller);
        }

        public override string ToString()
        {
            return "ControllerEnableMsg: " +
            "\ncontroller: " + controller.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
