//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ControlStatusMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/ControlStatus";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double reference;
        public double current;
        public double error;

        public ControlStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.reference = 0.0;
            this.current = 0.0;
            this.error = 0.0;
        }

        public ControlStatusMsg(Std.HeaderMsg header, double reference, double current, double error)
        {
            this.header = header;
            this.reference = reference;
            this.current = current;
            this.error = error;
        }

        public static ControlStatusMsg Deserialize(MessageDeserializer deserializer) => new ControlStatusMsg(deserializer);

        private ControlStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.reference);
            deserializer.Read(out this.current);
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.reference);
            serializer.Write(this.current);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "ControlStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nreference: " + reference.ToString() +
            "\ncurrent: " + current.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
