//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class DepthCommandMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/DepthCommand";
        public override string RosMessageName => k_RosMessageName;

        public bool active;
        public float depth;

        public DepthCommandMsg()
        {
            this.active = false;
            this.depth = 0.0f;
        }

        public DepthCommandMsg(bool active, float depth)
        {
            this.active = active;
            this.depth = depth;
        }

        public static DepthCommandMsg Deserialize(MessageDeserializer deserializer) => new DepthCommandMsg(deserializer);

        private DepthCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.active);
            deserializer.Read(out this.depth);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.active);
            serializer.Write(this.depth);
        }

        public override string ToString()
        {
            return "DepthCommandMsg: " +
            "\nactive: " + active.ToString() +
            "\ndepth: " + depth.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
