//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ElectricalCommandMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/ElectricalCommand";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte NO_COOLING_THRESH = -128;
        public sbyte cooling_threshold;
        public bool reset_copro;
        public bool reset_computer;
        public bool power_cycle_robot;
        public bool kill_robot_electrical;

        public ElectricalCommandMsg()
        {
            this.cooling_threshold = 0;
            this.reset_copro = false;
            this.reset_computer = false;
            this.power_cycle_robot = false;
            this.kill_robot_electrical = false;
        }

        public ElectricalCommandMsg(sbyte cooling_threshold, bool reset_copro, bool reset_computer, bool power_cycle_robot, bool kill_robot_electrical)
        {
            this.cooling_threshold = cooling_threshold;
            this.reset_copro = reset_copro;
            this.reset_computer = reset_computer;
            this.power_cycle_robot = power_cycle_robot;
            this.kill_robot_electrical = kill_robot_electrical;
        }

        public static ElectricalCommandMsg Deserialize(MessageDeserializer deserializer) => new ElectricalCommandMsg(deserializer);

        private ElectricalCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cooling_threshold);
            deserializer.Read(out this.reset_copro);
            deserializer.Read(out this.reset_computer);
            deserializer.Read(out this.power_cycle_robot);
            deserializer.Read(out this.kill_robot_electrical);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cooling_threshold);
            serializer.Write(this.reset_copro);
            serializer.Write(this.reset_computer);
            serializer.Write(this.power_cycle_robot);
            serializer.Write(this.kill_robot_electrical);
        }

        public override string ToString()
        {
            return "ElectricalCommandMsg: " +
            "\ncooling_threshold: " + cooling_threshold.ToString() +
            "\nreset_copro: " + reset_copro.ToString() +
            "\nreset_computer: " + reset_computer.ToString() +
            "\npower_cycle_robot: " + power_cycle_robot.ToString() +
            "\nkill_robot_electrical: " + kill_robot_electrical.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
