//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ElectricalReadingsMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/ElectricalReadings";
        public override string RosMessageName => k_RosMessageName;

        public const float NO_READING = -1f;
        public Std.HeaderMsg header;
        public float port_voltage;
        public float stbd_voltage;
        public float port_current;
        public float stbd_current;
        public float balanced_voltage;
        public float twelve_volt_voltage;
        public float five_volt_voltage;
        public float twelve_volt_current;
        public float five_volt_current;
        public float[] esc_current;

        public ElectricalReadingsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.port_voltage = 0.0f;
            this.stbd_voltage = 0.0f;
            this.port_current = 0.0f;
            this.stbd_current = 0.0f;
            this.balanced_voltage = 0.0f;
            this.twelve_volt_voltage = 0.0f;
            this.five_volt_voltage = 0.0f;
            this.twelve_volt_current = 0.0f;
            this.five_volt_current = 0.0f;
            this.esc_current = new float[8];
        }

        public ElectricalReadingsMsg(Std.HeaderMsg header, float port_voltage, float stbd_voltage, float port_current, float stbd_current, float balanced_voltage, float twelve_volt_voltage, float five_volt_voltage, float twelve_volt_current, float five_volt_current, float[] esc_current)
        {
            this.header = header;
            this.port_voltage = port_voltage;
            this.stbd_voltage = stbd_voltage;
            this.port_current = port_current;
            this.stbd_current = stbd_current;
            this.balanced_voltage = balanced_voltage;
            this.twelve_volt_voltage = twelve_volt_voltage;
            this.five_volt_voltage = five_volt_voltage;
            this.twelve_volt_current = twelve_volt_current;
            this.five_volt_current = five_volt_current;
            this.esc_current = esc_current;
        }

        public static ElectricalReadingsMsg Deserialize(MessageDeserializer deserializer) => new ElectricalReadingsMsg(deserializer);

        private ElectricalReadingsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.port_voltage);
            deserializer.Read(out this.stbd_voltage);
            deserializer.Read(out this.port_current);
            deserializer.Read(out this.stbd_current);
            deserializer.Read(out this.balanced_voltage);
            deserializer.Read(out this.twelve_volt_voltage);
            deserializer.Read(out this.five_volt_voltage);
            deserializer.Read(out this.twelve_volt_current);
            deserializer.Read(out this.five_volt_current);
            deserializer.Read(out this.esc_current, sizeof(float), 8);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.port_voltage);
            serializer.Write(this.stbd_voltage);
            serializer.Write(this.port_current);
            serializer.Write(this.stbd_current);
            serializer.Write(this.balanced_voltage);
            serializer.Write(this.twelve_volt_voltage);
            serializer.Write(this.five_volt_voltage);
            serializer.Write(this.twelve_volt_current);
            serializer.Write(this.five_volt_current);
            serializer.Write(this.esc_current);
        }

        public override string ToString()
        {
            return "ElectricalReadingsMsg: " +
            "\nheader: " + header.ToString() +
            "\nport_voltage: " + port_voltage.ToString() +
            "\nstbd_voltage: " + stbd_voltage.ToString() +
            "\nport_current: " + port_current.ToString() +
            "\nstbd_current: " + stbd_current.ToString() +
            "\nbalanced_voltage: " + balanced_voltage.ToString() +
            "\ntwelve_volt_voltage: " + twelve_volt_voltage.ToString() +
            "\nfive_volt_voltage: " + five_volt_voltage.ToString() +
            "\ntwelve_volt_current: " + twelve_volt_current.ToString() +
            "\nfive_volt_current: " + five_volt_current.ToString() +
            "\nesc_current: " + System.String.Join(", ", esc_current.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
