//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class LightingCommandMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/LightingCommand";
        public override string RosMessageName => k_RosMessageName;

        public byte light_1_brightness_percentage;
        public byte light_2_brightness_percentage;

        public LightingCommandMsg()
        {
            this.light_1_brightness_percentage = 0;
            this.light_2_brightness_percentage = 0;
        }

        public LightingCommandMsg(byte light_1_brightness_percentage, byte light_2_brightness_percentage)
        {
            this.light_1_brightness_percentage = light_1_brightness_percentage;
            this.light_2_brightness_percentage = light_2_brightness_percentage;
        }

        public static LightingCommandMsg Deserialize(MessageDeserializer deserializer) => new LightingCommandMsg(deserializer);

        private LightingCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.light_1_brightness_percentage);
            deserializer.Read(out this.light_2_brightness_percentage);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.light_1_brightness_percentage);
            serializer.Write(this.light_2_brightness_percentage);
        }

        public override string ToString()
        {
            return "LightingCommandMsg: " +
            "\nlight_1_brightness_percentage: " + light_1_brightness_percentage.ToString() +
            "\nlight_2_brightness_percentage: " + light_2_brightness_percentage.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
