//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class MissionStateMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/MissionState";
        public override string RosMessageName => k_RosMessageName;

        public sbyte[] mission_id;
        public sbyte[] task_completed;

        public MissionStateMsg()
        {
            this.mission_id = new sbyte[0];
            this.task_completed = new sbyte[0];
        }

        public MissionStateMsg(sbyte[] mission_id, sbyte[] task_completed)
        {
            this.mission_id = mission_id;
            this.task_completed = task_completed;
        }

        public static MissionStateMsg Deserialize(MessageDeserializer deserializer) => new MissionStateMsg(deserializer);

        private MissionStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mission_id, sizeof(sbyte), deserializer.ReadLength());
            deserializer.Read(out this.task_completed, sizeof(sbyte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.mission_id);
            serializer.Write(this.mission_id);
            serializer.WriteLength(this.task_completed);
            serializer.Write(this.task_completed);
        }

        public override string ToString()
        {
            return "MissionStateMsg: " +
            "\nmission_id: " + System.String.Join(", ", mission_id.ToList()) +
            "\ntask_completed: " + System.String.Join(", ", task_completed.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
