//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class NetLoadMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/NetLoad";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.Vector3Msg force;
        public Geometry.Vector3Msg moment;

        public NetLoadMsg()
        {
            this.header = new Std.HeaderMsg();
            this.force = new Geometry.Vector3Msg();
            this.moment = new Geometry.Vector3Msg();
        }

        public NetLoadMsg(Std.HeaderMsg header, Geometry.Vector3Msg force, Geometry.Vector3Msg moment)
        {
            this.header = header;
            this.force = force;
            this.moment = moment;
        }

        public static NetLoadMsg Deserialize(MessageDeserializer deserializer) => new NetLoadMsg(deserializer);

        private NetLoadMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.force = Geometry.Vector3Msg.Deserialize(deserializer);
            this.moment = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.force);
            serializer.Write(this.moment);
        }

        public override string ToString()
        {
            return "NetLoadMsg: " +
            "\nheader: " + header.ToString() +
            "\nforce: " + force.ToString() +
            "\nmoment: " + moment.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
