//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ObjectMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/Object";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string object_name;
        //  Bounding Box width in pixels. Useful for controlling an approximate distance.
        public int bbox_width;
        public int bbox_height;
        //  BBox Center position in pixels, relative to camera center (follows vehicle coord frame)
        public Geometry.PointMsg pos;

        public ObjectMsg()
        {
            this.header = new Std.HeaderMsg();
            this.object_name = "";
            this.bbox_width = 0;
            this.bbox_height = 0;
            this.pos = new Geometry.PointMsg();
        }

        public ObjectMsg(Std.HeaderMsg header, string object_name, int bbox_width, int bbox_height, Geometry.PointMsg pos)
        {
            this.header = header;
            this.object_name = object_name;
            this.bbox_width = bbox_width;
            this.bbox_height = bbox_height;
            this.pos = pos;
        }

        public static ObjectMsg Deserialize(MessageDeserializer deserializer) => new ObjectMsg(deserializer);

        private ObjectMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.object_name);
            deserializer.Read(out this.bbox_width);
            deserializer.Read(out this.bbox_height);
            this.pos = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.object_name);
            serializer.Write(this.bbox_width);
            serializer.Write(this.bbox_height);
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "ObjectMsg: " +
            "\nheader: " + header.ToString() +
            "\nobject_name: " + object_name.ToString() +
            "\nbbox_width: " + bbox_width.ToString() +
            "\nbbox_height: " + bbox_height.ToString() +
            "\npos: " + pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
