//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class PoleDataMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/PoleData";
        public override string RosMessageName => k_RosMessageName;

        public float roll_correction;
        public sbyte beam_thickness;

        public PoleDataMsg()
        {
            this.roll_correction = 0.0f;
            this.beam_thickness = 0;
        }

        public PoleDataMsg(float roll_correction, sbyte beam_thickness)
        {
            this.roll_correction = roll_correction;
            this.beam_thickness = beam_thickness;
        }

        public static PoleDataMsg Deserialize(MessageDeserializer deserializer) => new PoleDataMsg(deserializer);

        private PoleDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.roll_correction);
            deserializer.Read(out this.beam_thickness);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.roll_correction);
            serializer.Write(this.beam_thickness);
        }

        public override string ToString()
        {
            return "PoleDataMsg: " +
            "\nroll_correction: " + roll_correction.ToString() +
            "\nbeam_thickness: " + beam_thickness.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
