//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class PwmStampedMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/PwmStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public ushort[] pwm;

        public PwmStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pwm = new ushort[8];
        }

        public PwmStampedMsg(Std.HeaderMsg header, ushort[] pwm)
        {
            this.header = header;
            this.pwm = pwm;
        }

        public static PwmStampedMsg Deserialize(MessageDeserializer deserializer) => new PwmStampedMsg(deserializer);

        private PwmStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.pwm, sizeof(ushort), 8);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pwm);
        }

        public override string ToString()
        {
            return "PwmStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\npwm: " + System.String.Join(", ", pwm.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
