//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ResetControlsMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/ResetControls";
        public override string RosMessageName => k_RosMessageName;

        public bool reset_pwm;

        public ResetControlsMsg()
        {
            this.reset_pwm = false;
        }

        public ResetControlsMsg(bool reset_pwm)
        {
            this.reset_pwm = reset_pwm;
        }

        public static ResetControlsMsg Deserialize(MessageDeserializer deserializer) => new ResetControlsMsg(deserializer);

        private ResetControlsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.reset_pwm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.reset_pwm);
        }

        public override string ToString()
        {
            return "ResetControlsMsg: " +
            "\nreset_pwm: " + reset_pwm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
