//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class StatusLightMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/StatusLight";
        public override string RosMessageName => k_RosMessageName;

        public bool green1;
        public bool red1;
        public bool green2;
        public bool red2;
        public bool green3;
        public bool red3;
        public bool green4;
        public bool red4;

        public StatusLightMsg()
        {
            this.green1 = false;
            this.red1 = false;
            this.green2 = false;
            this.red2 = false;
            this.green3 = false;
            this.red3 = false;
            this.green4 = false;
            this.red4 = false;
        }

        public StatusLightMsg(bool green1, bool red1, bool green2, bool red2, bool green3, bool red3, bool green4, bool red4)
        {
            this.green1 = green1;
            this.red1 = red1;
            this.green2 = green2;
            this.red2 = red2;
            this.green3 = green3;
            this.red3 = red3;
            this.green4 = green4;
            this.red4 = red4;
        }

        public static StatusLightMsg Deserialize(MessageDeserializer deserializer) => new StatusLightMsg(deserializer);

        private StatusLightMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.green1);
            deserializer.Read(out this.red1);
            deserializer.Read(out this.green2);
            deserializer.Read(out this.red2);
            deserializer.Read(out this.green3);
            deserializer.Read(out this.red3);
            deserializer.Read(out this.green4);
            deserializer.Read(out this.red4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.green1);
            serializer.Write(this.red1);
            serializer.Write(this.green2);
            serializer.Write(this.red2);
            serializer.Write(this.green3);
            serializer.Write(this.red3);
            serializer.Write(this.green4);
            serializer.Write(this.red4);
        }

        public override string ToString()
        {
            return "StatusLightMsg: " +
            "\ngreen1: " + green1.ToString() +
            "\nred1: " + red1.ToString() +
            "\ngreen2: " + green2.ToString() +
            "\nred2: " + red2.ToString() +
            "\ngreen3: " + green3.ToString() +
            "\nred3: " + red3.ToString() +
            "\ngreen4: " + green4.ToString() +
            "\nred4: " + red4.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
