//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class SwitchStateMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/SwitchState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public bool kill;
        public bool sw1;
        public bool sw2;
        public bool sw3;
        public bool sw4;
        public bool sw5;

        public SwitchStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.kill = false;
            this.sw1 = false;
            this.sw2 = false;
            this.sw3 = false;
            this.sw4 = false;
            this.sw5 = false;
        }

        public SwitchStateMsg(Std.HeaderMsg header, bool kill, bool sw1, bool sw2, bool sw3, bool sw4, bool sw5)
        {
            this.header = header;
            this.kill = kill;
            this.sw1 = sw1;
            this.sw2 = sw2;
            this.sw3 = sw3;
            this.sw4 = sw4;
            this.sw5 = sw5;
        }

        public static SwitchStateMsg Deserialize(MessageDeserializer deserializer) => new SwitchStateMsg(deserializer);

        private SwitchStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.kill);
            deserializer.Read(out this.sw1);
            deserializer.Read(out this.sw2);
            deserializer.Read(out this.sw3);
            deserializer.Read(out this.sw4);
            deserializer.Read(out this.sw5);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.kill);
            serializer.Write(this.sw1);
            serializer.Write(this.sw2);
            serializer.Write(this.sw3);
            serializer.Write(this.sw4);
            serializer.Write(this.sw5);
        }

        public override string ToString()
        {
            return "SwitchStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nkill: " + kill.ToString() +
            "\nsw1: " + sw1.ToString() +
            "\nsw2: " + sw2.ToString() +
            "\nsw3: " + sw3.ToString() +
            "\nsw4: " + sw4.ToString() +
            "\nsw5: " + sw5.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
