//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class TaskInfoMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/TaskInfo";
        public override string RosMessageName => k_RosMessageName;

        public sbyte task_id;
        public string task_name;
        public sbyte alignment_plane;
        //  YZ or XY

        public TaskInfoMsg()
        {
            this.task_id = 0;
            this.task_name = "";
            this.alignment_plane = 0;
        }

        public TaskInfoMsg(sbyte task_id, string task_name, sbyte alignment_plane)
        {
            this.task_id = task_id;
            this.task_name = task_name;
            this.alignment_plane = alignment_plane;
        }

        public static TaskInfoMsg Deserialize(MessageDeserializer deserializer) => new TaskInfoMsg(deserializer);

        private TaskInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.task_name);
            deserializer.Read(out this.alignment_plane);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.task_name);
            serializer.Write(this.alignment_plane);
        }

        public override string ToString()
        {
            return "TaskInfoMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\ntask_name: " + task_name.ToString() +
            "\nalignment_plane: " + alignment_plane.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
