//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ThrustStampedMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/ThrustStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public ThrustMsg force;

        public ThrustStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.force = new ThrustMsg();
        }

        public ThrustStampedMsg(Std.HeaderMsg header, ThrustMsg force)
        {
            this.header = header;
            this.force = force;
        }

        public static ThrustStampedMsg Deserialize(MessageDeserializer deserializer) => new ThrustStampedMsg(deserializer);

        private ThrustStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.force = ThrustMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.force);
        }

        public override string ToString()
        {
            return "ThrustStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\nforce: " + force.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
