//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Riptide
{
    [Serializable]
    public class ThrustMsg : Message
    {
        public const string k_RosMessageName = "riptide_msgs2/Thrust";
        public override string RosMessageName => k_RosMessageName;

        public float vector_port_fwd;
        public float vector_stbd_fwd;
        public float vector_port_aft;
        public float vector_stbd_aft;
        public float heave_port_fwd;
        public float heave_stbd_fwd;
        public float heave_port_aft;
        public float heave_stbd_aft;
        //  Used to index controllers within the pwm controller
        public const sbyte VPF = 0;
        public const sbyte VSF = 1;
        public const sbyte VPA = 2;
        public const sbyte VSA = 3;
        public const sbyte HPF = 4;
        public const sbyte HSF = 5;
        public const sbyte HPA = 6;
        public const sbyte HSA = 7;

        public ThrustMsg()
        {
            this.vector_port_fwd = 0.0f;
            this.vector_stbd_fwd = 0.0f;
            this.vector_port_aft = 0.0f;
            this.vector_stbd_aft = 0.0f;
            this.heave_port_fwd = 0.0f;
            this.heave_stbd_fwd = 0.0f;
            this.heave_port_aft = 0.0f;
            this.heave_stbd_aft = 0.0f;
        }

        public ThrustMsg(float vector_port_fwd, float vector_stbd_fwd, float vector_port_aft, float vector_stbd_aft, float heave_port_fwd, float heave_stbd_fwd, float heave_port_aft, float heave_stbd_aft)
        {
            this.vector_port_fwd = vector_port_fwd;
            this.vector_stbd_fwd = vector_stbd_fwd;
            this.vector_port_aft = vector_port_aft;
            this.vector_stbd_aft = vector_stbd_aft;
            this.heave_port_fwd = heave_port_fwd;
            this.heave_stbd_fwd = heave_stbd_fwd;
            this.heave_port_aft = heave_port_aft;
            this.heave_stbd_aft = heave_stbd_aft;
        }

        public static ThrustMsg Deserialize(MessageDeserializer deserializer) => new ThrustMsg(deserializer);

        private ThrustMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vector_port_fwd);
            deserializer.Read(out this.vector_stbd_fwd);
            deserializer.Read(out this.vector_port_aft);
            deserializer.Read(out this.vector_stbd_aft);
            deserializer.Read(out this.heave_port_fwd);
            deserializer.Read(out this.heave_stbd_fwd);
            deserializer.Read(out this.heave_port_aft);
            deserializer.Read(out this.heave_stbd_aft);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vector_port_fwd);
            serializer.Write(this.vector_stbd_fwd);
            serializer.Write(this.vector_port_aft);
            serializer.Write(this.vector_stbd_aft);
            serializer.Write(this.heave_port_fwd);
            serializer.Write(this.heave_stbd_fwd);
            serializer.Write(this.heave_port_aft);
            serializer.Write(this.heave_stbd_aft);
        }

        public override string ToString()
        {
            return "ThrustMsg: " +
            "\nvector_port_fwd: " + vector_port_fwd.ToString() +
            "\nvector_stbd_fwd: " + vector_stbd_fwd.ToString() +
            "\nvector_port_aft: " + vector_port_aft.ToString() +
            "\nvector_stbd_aft: " + vector_stbd_aft.ToString() +
            "\nheave_port_fwd: " + heave_port_fwd.ToString() +
            "\nheave_stbd_fwd: " + heave_stbd_fwd.ToString() +
            "\nheave_port_aft: " + heave_port_aft.ToString() +
            "\nheave_stbd_aft: " + heave_stbd_aft.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
